[build-system]
requires = [
  "scikit-build-core>=0.5.0",
  "pybind11>=2.10.0",
  ]
build-backend = "scikit_build_core.build"


[project]
name = "rosen-cpp"
dynamic = ["version"]
description = "Example package for demonstration"
readme = "README.md"
license = { text = "MIT" }  # SPDX short identifier
authors = [
  { name = "Matthew Feickert", email = "matthew.feickert@cern.ch" },
]
maintainers = [
  { name = "Matthew Feickert", email = "matthew.feickert@cern.ch" },
]
requires-python = ">=3.10"

dependencies = [
    "scipy>=1.6.0",
    "numpy",  # compatible versions controlled through scipy
]

classifiers = [
  "Development Status :: 4 - Beta",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Scientific/Engineering :: Physics",
]

[project.urls]
Homepage = "https://github.com/matthewfeickert-talks/talk-odsl-forum-seminar-2023"
Documentation = "https://github.com/matthewfeickert-talks/talk-odsl-forum-seminar-2023"
"Bug Tracker" = "https://github.com/matthewfeickert-talks/talk-odsl-forum-seminar-2023/issues"

[tool.scikit-build]
metadata.version.provider = "scikit_build_core.metadata.setuptools_scm"

[tool.setuptools_scm]
# Ignore the commit hash in version
local_scheme = "no-local-version"
# Need to give root as we aren't at the same level as the git repo
root = "../.."

[[tool.scikit-build.generate]]
path = "rosen_cpp/_version.py"
template = '''
version = "${version}"
'''

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]
preview = ["pixi-build"]

[tool.pixi.workspace.build-variants]
python = ["3.10.*", "3.11.*", "3.12.*", "3.13.*", "3.14.*"]

[tool.pixi.dependencies]
rosen-cpp = { path = "." }

[tool.pixi.tasks]

[tool.pixi.package]
name = "rosen-cpp"
# As of Pixi v0.67.2 can't pickup dynamic metadata
# with package.build.config.ignore-pyproject-manifest = false
version = "0.0.3"

[tool.pixi.package.build]
backend = { name = "pixi-build-python", version = "*" }
# c.f. https://pixi.prefix.dev/latest/build/backends/pixi-build-python/#compilers
# c.f. https://pixi.prefix.dev/latest/build/backends/pixi-build-python/#ignore-pypi-mapping
config = { compilers = ["cxx"], ignore-pypi-mapping = false }

[tool.pixi.package.build-dependencies]
cmake = ">=4.2.0"
ninja = ">=1.13.0"

[tool.pixi.package.host-dependencies]
python = "*"
uv = "*"
setuptools_scm = "*"
# Unneeded given package.build.config.ignore-pypi-mapping = false
# scikit-build-core = ">=0.5.0"
# pybind11 = ">=2.10.0"

# This table is unneeded given package.build.config.ignore-pypi-mapping = false
# [tool.pixi.package.run-dependencies]
# scipy = ">=1.6.0"

[tool.pixi.feature.py310.dependencies]
python = "3.10.*"

[tool.pixi.feature.py311.dependencies]
python = "3.11.*"

[tool.pixi.feature.py312.dependencies]
python = "3.12.*"

[tool.pixi.feature.py313.dependencies]
python = "3.13.*"

[tool.pixi.feature.py314.dependencies]
python = "3.14.*"

[tool.pixi.feature.tests.dependencies]
pytest = "*"

[tool.pixi.feature.tests.tasks.tests]
description = "Run tests with pytest"
cmd = "pytest tests/ -v"
default-environment = "py314"

[tool.pixi.environments]
py310 = { features = ["py310", "tests"], solve-group = "py310" }
py311 = { features = ["py311", "tests"], solve-group = "py311" }
py312 = { features = ["py312", "tests"], solve-group = "py312" }
py313 = { features = ["py313", "tests"], solve-group = "py313" }
py314 = { features = ["py314", "tests"], solve-group = "py314" }
