name: Deploy GitHub Pages

on:
  push:
    branches: ["main"]
    tags: [v*]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Setup build for deployment
        run: |
          mkdir -p _build
          cp -r assets _build/
          cp -r figures _build/
          cp index.html _build/
          cp talk.md _build/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '_build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
